# Generated by Django 3.2.8 on 2021-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211024_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='food',
            name='consumed_in_period',
            field=models.ManyToManyField(blank=True, to='mainapp.TimeWindow'),
        ),
    ]
